# Generated by Django 4.2.16 on 2026-04-07 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_conversation_cpu_percent_conversation_memory_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='timed_out',
            field=models.BooleanField(default=False),
        ),
    ]
