# Generated by Django 4.2.16 on 2026-04-08 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_conversation_timed_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='timeout_setting_sec',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
