# Generated by Django 4.2.16 on 2026-04-08 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_conversation_timeout_setting_sec'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='user_aborted',
            field=models.BooleanField(default=False),
        ),
    ]
