# Generated by Django 4.2.16 on 2026-04-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_conversation_user_aborted'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='mode',
            field=models.CharField(default='通常', max_length=10),
        ),
    ]
