# Generated by Django 4.2.16 on 2026-04-08 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_conversation_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpreadsheetLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'スプレッドシート',
                'verbose_name_plural': 'スプレッドシート',
                'managed': False,
            },
        ),
    ]
