# Generated by Django 4.2.16 on 2026-04-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_spreadsheetlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='キー')),
                ('value', models.TextField(verbose_name='値')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='説明')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '設定',
                'verbose_name_plural': '設定',
            },
        ),
    ]
